version: '2'

services:
  java:
    tty: true # Enables debugging capabilities when attached to this container.
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: ["tail", "-f", "/dev/null"] # To keep the container running
    volumes:
      - .:/app